'use server'

import { adminDb, adminAuth } from "@/firebase/admin";
import { cookies } from "next/headers";
import { cache } from "react";
import { unstable_cache, revalidateTag } from "next/cache";


/**
 * ==========================================
 * SYNC USER ACCOUNT TO FIRESTORE
 * ==========================================
 * Following a successful Firebase Auth registration (whether natively or via Google), 
 * this Server Action creates or updates the user's permanent database record in Firestore.
 * 
 * @param params Contains the user's secure UID, and optionally their Name, Email, and Avatar Photo.
 */
export async function signUp(params: SignUpParams) {
    const { uid, name, email, photoURL } = params;
    
    try {
        // 1. Fetch existing user document to check if they already have an avatar
        const userRef = adminDb.collection("users").doc(uid);
        const userDoc = await userRef.get();

        // 2. We use `{ merge: true }` so that if a user logs in repeatedly with Google, 
        // we don't erase their original `createdAt` timestamp.
        const updateData: any = {
            name: name || userDoc.data()?.name || "",
            email: email || userDoc.data()?.email || "",
            ...( !userDoc.exists && { createdAt: new Date().toISOString() } ),
        };

        // 3. SILENT PRESERVATION: Only overwrite the photo if the user DOES NOT already have one!
        if (!userDoc.exists || !userDoc.data()?.photoURL) {
            updateData.photoURL = photoURL || "";
        }

        await userRef.set(updateData, { merge: true });

        return {
            success: true,
            message: "Account synced successfully."
        };
    } catch (e: any) {
        console.error("Error syncing user data to Firestore:", e);

        return {
            success: false,
            message: "Failed to sync account."
        }
    }
}

/**
 * ==========================================
 * RECORD USER SIGN-IN
 * ==========================================
 * Used to update the user's database record upon a successful login.
 * Useful for tracking actively used accounts by updating `lastLoginAt`.
 * 
 * @param uid The user's secure Firebase UID.
 */
export async function signIn(uid: string) {
    try {
        await adminDb.collection("users").doc(uid).set({
            lastLoginAt: new Date().toISOString()
        }, { merge: true });

        return {
            success: true,
            message: "Sign-in recorded successfully."
        };
    } catch (error) {
        console.error("Error recording sign-in:", error);
        return {
            success: false,
            message: "Failed to record sign-in."
        };
    }
}

/**
 * ==========================================
 * VERIFY USER EMAIL IDENTIFIER
 * ==========================================
 * Securely checks if an email is already registered in Firebase Auth without attempting to log in.
 */
export async function checkUserExists(email: string) {
    try {
        await adminAuth.getUserByEmail(email);
        return { 
            exists: true, 
            success: true 
        };
    } catch (error: any) {
        if (error.code === 'auth/user-not-found') {
            return { 
                exists: false, 
                success: false, 
                message: 'User does not exist. Create an account instead.' 
            };
        }
        return { exists: false, success: false, message: 'An error occurred during verification.' };
    }
}

/**
 * ==========================================
 * CREATE SECURE SERVER SESSION COOKIE
 * ==========================================
 * Used to keep the Next.js Server (Middlewares & Layouts) in sync with the Client's auth state.
 * Takes the raw Token generated by Firebase Client auth and trades it for a secure HttpOnly Session Cookie.
 * 
 * @param idToken The raw authentication token from `userCredential.user.getIdToken()`
 */
export async function setSessionCookie(idToken: string) {
    try {
        // Create session cookie to last for exactly 1 week (7 days)
        const expiresIn = 60 * 60 * 24 * 7 * 1000; 
        
        // 1. Ask Firebase Admin to verify the client token and mint a long-lived cookie response
        const sessionCookie = await adminAuth.createSessionCookie(idToken, { expiresIn });
        
        // 2. Set the newly minted cookie using the Next.js 15 Cookie API securely.
        const cookieStore = await cookies();
        cookieStore.set('session', sessionCookie, {
            maxAge: expiresIn / 1000, // Cookie maxAge expects seconds, not milliseconds!
            httpOnly: true, // Crucial: Prevents JavaScript XSS attacks from reading the auth token!
            secure: process.env.NODE_ENV === 'production', // Only require HTTPS in real production environments
            path: '/', // Ensure the cookie is readable globally across the entire app
            sameSite: 'lax', // Protects against Cross-Site Request Forgery (CSRF) attacks
        });

        return { success: true };
    } catch (error) {
        console.error("Failed to create session cookie", error);
        return { success: false, message: "Authentication failed. Could not verify session server-side." };
    }
}

/**
 * ==========================================
 * DESTROY SERVER SESSION COOKIE
 * ==========================================
 * Logs the user out securely from the server perspective by nuking the 'session' cookie.
 */
export async function removeSession() {
    try {
        const cookieStore = await cookies();
        cookieStore.delete('session');
        return { success: true };
    } catch (error) {
        console.error("Failed to remove session cookie", error);
        return { success: false };
    }
}

/**
 * ==========================================
 * SECURELY FETCH CURRENT USER (SERVER ONLY)
 * ==========================================
 * Next.js Server Components call this to invisibly grab the user's data from Firestore 
 * using their HTTPOnly Session Cookie.
 * 
 * ✅ Wrapped with React cache() — within a single server render, no matter how many
 * components call this (layout + page), the Firebase verifySessionCookie + Firestore
 * lookup runs ONLY ONCE. Subsequent calls reuse the cached result instantly.
 */
export const getCurrentUser = cache(async () => {
    try {
        const cookieStore = await cookies();
        const sessionCookie = cookieStore.get('session')?.value;

        if (!sessionCookie) return null;

        // ✅ checkRevoked: false = local-only cryptographic JWT verification (~0ms).
        //    checkRevoked: true = makes an HTTP request to Google's servers on EVERY render
        //    which adds 3-15 seconds from India. The cookie already has 7-day expiry + 
        //    cryptographic signature. removeSession() handles logout securely without needing this.
        const decodedClaims = await adminAuth.verifySessionCookie(sessionCookie, false);

        // Fetch user profile from Firestore (cached separately by unstable_cache)
        const userDoc = await adminDb.collection("users").doc(decodedClaims.uid).get();
        const data = userDoc.data();

        if (!userDoc.exists || !data) return null;

        return {
            uid: decodedClaims.uid,
            name: data.name || "User",
            email: data.email,
            photoURL: data.photoURL || null,
            plan: data.plan || "free",
            planExpiresAt: data.planExpiresAt || null,
        };
    } catch (error) {
        return null;
    }
});

/**
 * ==========================================
 * BOOLEAN AUTH GUARD
 * ==========================================
 * Returns a simple true/false boolean designed specifically to rapidly block Next.js Layouts.
 * Exactly matches your tutor's architecture.
 */
export async function isAuthenticated() {
    const user = await getCurrentUser();
    return !!user;
}

/**
 * ==========================================
 * FETCH RECENT USERS (FOR SOCIAL PROOF)
 * ==========================================
 * Retrieves a list of recent users who have signed up, specifically for their avatars.
 * Includes retry logic to handle transient network errors (e.g. ECONNRESET) gracefully.
 * @param limit The maximum number of users to retrieve
 */
export async function getRecentUsers(limitCount: number = 4): Promise<string[]> {
    const MAX_RETRIES = 2;
    const RETRY_DELAY_MS = 500;

    for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
        try {
            const usersSnapshot = await adminDb.collection("users")
                .orderBy("createdAt", "desc")
                .limit(limitCount)
                .get();

            const users: string[] = [];

            usersSnapshot.forEach((doc) => {
                const data = doc.data();
                if (data.photoURL) {
                    users.push(data.photoURL);
                }
            });

            return users;
        } catch (error: any) {
            const isNetworkError =
                error?.code === "ECONNRESET" ||
                error?.errno === "ECONNRESET" ||
                error?.code === "ENOTFOUND" ||
                error?.errno === "ENOTFOUND" ||
                error?.code === "EAI_AGAIN" ||
                error?.errno === "EAI_AGAIN" ||
                error?.type === "system" ||
                error?.message?.includes("ECONNRESET") ||
                error?.message?.includes("ENOTFOUND") ||
                error?.message?.includes("EAI_AGAIN") ||
                error?.message?.includes("fetch failed");

            if (isNetworkError && attempt < MAX_RETRIES) {
                // Transient network hiccup — wait briefly and retry
                await new Promise((resolve) => setTimeout(resolve, RETRY_DELAY_MS * (attempt + 1)));
                continue;
            }

            // Non-retryable error or retries exhausted — fail silently, page still renders with fallback avatars
            console.warn(`Failed to fetch recent users (attempt ${attempt + 1}/${MAX_RETRIES + 1}): ${error.message || error}`);
            return [];
        }
    }

    return [];
}

/**
 * ==========================================
 * FETCH USER'S PRIVATE INTERVIEWS
 * ==========================================
 * Retrieves the current user's past interviews from Firestore.
 * 
 * ✅ Wrapped with unstable_cache — results are cached server-side for 60 seconds per user.
 * Navigating away and back to the dashboard reuses cached data instantly.
 * Call revalidateTag(`interviews-${userId}`) after creating a new interview to bust the cache.
 */
export async function getInterviewsByUserId(userId: string) {
    const fetcher = unstable_cache(
        async (uid: string) => {
            try {
                const interviewsSnapshot = await adminDb.collection("interviews")
                    .where("userId", "==", uid)
                    .get();

                const interviews = interviewsSnapshot.docs.map((doc) => ({
                    id: doc.id,
                    ...doc.data()
                })).sort((a: any, b: any) => {
                    const dateA = a.createdAt ? new Date(a.createdAt).getTime() : 0;
                    const dateB = b.createdAt ? new Date(b.createdAt).getTime() : 0;
                    return dateB - dateA;
                });

                return interviews;
            } catch (error) {
                console.error("Failed to fetch user interviews:", error);
                return [];
            }
        },
        [`interviews-${userId}`],           // unique cache key per user
        { revalidate: 60, tags: [`interviews-${userId}`] } // 60s TTL + tag for manual invalidation
    );

    return fetcher(userId);
}

/**
 * Call this after creating a new interview so the cache is immediately invalidated
 * and the dashboard shows the new interview on next render.
 */
export async function invalidateInterviewsCache(userId: string) {
    try {
        revalidateTag(`interviews-${userId}`, "max");
    } catch {
        // revalidateTag may not work outside request context — safe to ignore
    }
}

/**
 * ==========================================
 * UPDATE USER PROFILE
 * ==========================================
 * Updates the current user's profile data in Firestore.
 */
export async function updateProfileData(userId: string, data: { name?: string; photoURL?: string }) {
    try {
        await adminDb.collection("users").doc(userId).set(data, { merge: true });
        return { success: true, message: "Profile updated successfully." };
    } catch (error) {
        console.error("Failed to update profile:", error);
        return { success: false, message: "Failed to update profile." };
    }
}

/**
 * ==========================================
 * GET USER PLAN & INTERVIEW COUNT
 * ==========================================
 * Returns the user's active plan and their total interview count.
 * Used by the interview creation flow to gate access before showing the form.
 */
export async function getUserPlanAndCount(uid: string): Promise<{
    isPremium: boolean;
    plan: string;
    interviewCount: number;
}> {
    try {
        const [userDoc, interviewsSnap] = await Promise.all([
            adminDb.collection("users").doc(uid).get(),
            adminDb.collection("interviews").where("userId", "==", uid).get(),
        ]);

        const userData = userDoc.data();
        const plan = userData?.plan ?? "free";
        const planExpiresAt = userData?.planExpiresAt;

        const isPremium =
            plan !== "free" &&
            !!planExpiresAt &&
            new Date(planExpiresAt) > new Date();

        return { isPremium, plan, interviewCount: interviewsSnap.size };
    } catch {
        return { isPremium: false, plan: "free", interviewCount: 0 };
    }
}

